//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÄlytaloMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talo
    {
        public int TaloID { get; set; }
        public Nullable<int> SaunaID { get; set; }
        public Nullable<int> TaloLampoID { get; set; }
        public Nullable<int> ValoID { get; set; }
        public string TalonNimi { get; set; }
    
        public virtual Sauna Sauna { get; set; }
        public virtual TaloLampo TaloLampo { get; set; }
        public virtual Valo Valo { get; set; }
    }
}
